baseURL = 'https://kiro-community.github.io/book-of-kiro/'
languageCode = 'en-us'
title = 'Book of Kiro'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
